# Generated by Django 3.2 on 2021-06-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kala', '0003_auto_20210601_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
