# Generated by Django 3.2 on 2021-06-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kala', '0004_alter_checkout_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='product_id',
        ),
    ]
