# Generated by Django 3.2 on 2021-06-01 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kala', '0005_remove_checkout_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='order_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
