# Generated by Django 3.2 on 2021-06-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kala', '0007_alter_checkout_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
